// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"

	entity "github.com/mandarine-io/backend/internal/persistence/entity"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/mandarine-io/backend/internal/persistence/repo"

	uuid "github.com/google/uuid"
)

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserRepositoryMock) CreateUser(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepositoryMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *UserRepositoryMock_Expecter) CreateUser(ctx interface{}, user interface{}) *UserRepositoryMock_CreateUser_Call {
	return &UserRepositoryMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *UserRepositoryMock_CreateUser_Call) Run(run func(ctx context.Context, user *entity.User)) *UserRepositoryMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserRepositoryMock_CreateUser_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_CreateUser_Call) RunAndReturn(run func(context.Context, *entity.User) (*entity.User, error)) *UserRepositoryMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredUser provides a mock function with given fields: ctx
func (_m *UserRepositoryMock) DeleteExpiredUser(ctx context.Context) (*entity.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_DeleteExpiredUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredUser'
type UserRepositoryMock_DeleteExpiredUser_Call struct {
	*mock.Call
}

// DeleteExpiredUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepositoryMock_Expecter) DeleteExpiredUser(ctx interface{}) *UserRepositoryMock_DeleteExpiredUser_Call {
	return &UserRepositoryMock_DeleteExpiredUser_Call{Call: _e.mock.On("DeleteExpiredUser", ctx)}
}

func (_c *UserRepositoryMock_DeleteExpiredUser_Call) Run(run func(ctx context.Context)) *UserRepositoryMock_DeleteExpiredUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserRepositoryMock_DeleteExpiredUser_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_DeleteExpiredUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_DeleteExpiredUser_Call) RunAndReturn(run func(context.Context) (*entity.User, error)) *UserRepositoryMock_DeleteExpiredUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepositoryMock) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsUserByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_ExistsUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsUserByEmail'
type UserRepositoryMock_ExistsUserByEmail_Call struct {
	*mock.Call
}

// ExistsUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepositoryMock_Expecter) ExistsUserByEmail(ctx interface{}, email interface{}) *UserRepositoryMock_ExistsUserByEmail_Call {
	return &UserRepositoryMock_ExistsUserByEmail_Call{Call: _e.mock.On("ExistsUserByEmail", ctx, email)}
}

func (_c *UserRepositoryMock_ExistsUserByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepositoryMock_ExistsUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByEmail_Call) Return(_a0 bool, _a1 error) *UserRepositoryMock_ExistsUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByEmail_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *UserRepositoryMock_ExistsUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsUserByID provides a mock function with given fields: ctx, id
func (_m *UserRepositoryMock) ExistsUserByID(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsUserByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_ExistsUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsUserByID'
type UserRepositoryMock_ExistsUserByID_Call struct {
	*mock.Call
}

// ExistsUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepositoryMock_Expecter) ExistsUserByID(ctx interface{}, id interface{}) *UserRepositoryMock_ExistsUserByID_Call {
	return &UserRepositoryMock_ExistsUserByID_Call{Call: _e.mock.On("ExistsUserByID", ctx, id)}
}

func (_c *UserRepositoryMock_ExistsUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepositoryMock_ExistsUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByID_Call) Return(_a0 bool, _a1 error) *UserRepositoryMock_ExistsUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *UserRepositoryMock_ExistsUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsUserByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepositoryMock) ExistsUserByUsername(ctx context.Context, username string) (bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsUserByUsername")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_ExistsUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsUserByUsername'
type UserRepositoryMock_ExistsUserByUsername_Call struct {
	*mock.Call
}

// ExistsUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepositoryMock_Expecter) ExistsUserByUsername(ctx interface{}, username interface{}) *UserRepositoryMock_ExistsUserByUsername_Call {
	return &UserRepositoryMock_ExistsUserByUsername_Call{Call: _e.mock.On("ExistsUserByUsername", ctx, username)}
}

func (_c *UserRepositoryMock_ExistsUserByUsername_Call) Run(run func(ctx context.Context, username string)) *UserRepositoryMock_ExistsUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByUsername_Call) Return(_a0 bool, _a1 error) *UserRepositoryMock_ExistsUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByUsername_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *UserRepositoryMock_ExistsUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsUserByUsernameOrEmail provides a mock function with given fields: ctx, username, email
func (_m *UserRepositoryMock) ExistsUserByUsernameOrEmail(ctx context.Context, username string, email string) (bool, error) {
	ret := _m.Called(ctx, username, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsUserByUsernameOrEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, username, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, username, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_ExistsUserByUsernameOrEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsUserByUsernameOrEmail'
type UserRepositoryMock_ExistsUserByUsernameOrEmail_Call struct {
	*mock.Call
}

// ExistsUserByUsernameOrEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
func (_e *UserRepositoryMock_Expecter) ExistsUserByUsernameOrEmail(ctx interface{}, username interface{}, email interface{}) *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call {
	return &UserRepositoryMock_ExistsUserByUsernameOrEmail_Call{Call: _e.mock.On("ExistsUserByUsernameOrEmail", ctx, username, email)}
}

func (_c *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call) Run(run func(ctx context.Context, username string, email string)) *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call) Return(_a0 bool, _a1 error) *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *UserRepositoryMock_ExistsUserByUsernameOrEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function with given fields: ctx, email, scopes
func (_m *UserRepositoryMock) FindUserByEmail(ctx context.Context, email string, scopes ...repo.Scope) (*entity.User, error) {
	_va := make([]interface{}, len(scopes))
	for _i := range scopes {
		_va[_i] = scopes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, email)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) (*entity.User, error)); ok {
		return rf(ctx, email, scopes...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) *entity.User); ok {
		r0 = rf(ctx, email, scopes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...repo.Scope) error); ok {
		r1 = rf(ctx, email, scopes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type UserRepositoryMock_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - scopes ...repo.Scope
func (_e *UserRepositoryMock_Expecter) FindUserByEmail(ctx interface{}, email interface{}, scopes ...interface{}) *UserRepositoryMock_FindUserByEmail_Call {
	return &UserRepositoryMock_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail",
		append([]interface{}{ctx, email}, scopes...)...)}
}

func (_c *UserRepositoryMock_FindUserByEmail_Call) Run(run func(ctx context.Context, email string, scopes ...repo.Scope)) *UserRepositoryMock_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repo.Scope, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(repo.Scope)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *UserRepositoryMock_FindUserByEmail_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindUserByEmail_Call) RunAndReturn(run func(context.Context, string, ...repo.Scope) (*entity.User, error)) *UserRepositoryMock_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: ctx, id, scopes
func (_m *UserRepositoryMock) FindUserByID(ctx context.Context, id uuid.UUID, scopes ...repo.Scope) (*entity.User, error) {
	_va := make([]interface{}, len(scopes))
	for _i := range scopes {
		_va[_i] = scopes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...repo.Scope) (*entity.User, error)); ok {
		return rf(ctx, id, scopes...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...repo.Scope) *entity.User); ok {
		r0 = rf(ctx, id, scopes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...repo.Scope) error); ok {
		r1 = rf(ctx, id, scopes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type UserRepositoryMock_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - scopes ...repo.Scope
func (_e *UserRepositoryMock_Expecter) FindUserByID(ctx interface{}, id interface{}, scopes ...interface{}) *UserRepositoryMock_FindUserByID_Call {
	return &UserRepositoryMock_FindUserByID_Call{Call: _e.mock.On("FindUserByID",
		append([]interface{}{ctx, id}, scopes...)...)}
}

func (_c *UserRepositoryMock_FindUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID, scopes ...repo.Scope)) *UserRepositoryMock_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repo.Scope, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(repo.Scope)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), variadicArgs...)
	})
	return _c
}

func (_c *UserRepositoryMock_FindUserByID_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, ...repo.Scope) (*entity.User, error)) *UserRepositoryMock_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function with given fields: ctx, username, scopes
func (_m *UserRepositoryMock) FindUserByUsername(ctx context.Context, username string, scopes ...repo.Scope) (*entity.User, error) {
	_va := make([]interface{}, len(scopes))
	for _i := range scopes {
		_va[_i] = scopes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, username)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) (*entity.User, error)); ok {
		return rf(ctx, username, scopes...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) *entity.User); ok {
		r0 = rf(ctx, username, scopes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...repo.Scope) error); ok {
		r1 = rf(ctx, username, scopes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type UserRepositoryMock_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - scopes ...repo.Scope
func (_e *UserRepositoryMock_Expecter) FindUserByUsername(ctx interface{}, username interface{}, scopes ...interface{}) *UserRepositoryMock_FindUserByUsername_Call {
	return &UserRepositoryMock_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername",
		append([]interface{}{ctx, username}, scopes...)...)}
}

func (_c *UserRepositoryMock_FindUserByUsername_Call) Run(run func(ctx context.Context, username string, scopes ...repo.Scope)) *UserRepositoryMock_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repo.Scope, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(repo.Scope)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *UserRepositoryMock_FindUserByUsername_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindUserByUsername_Call) RunAndReturn(run func(context.Context, string, ...repo.Scope) (*entity.User, error)) *UserRepositoryMock_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsernameOrEmail provides a mock function with given fields: ctx, login, scopes
func (_m *UserRepositoryMock) FindUserByUsernameOrEmail(ctx context.Context, login string, scopes ...repo.Scope) (*entity.User, error) {
	_va := make([]interface{}, len(scopes))
	for _i := range scopes {
		_va[_i] = scopes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, login)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsernameOrEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) (*entity.User, error)); ok {
		return rf(ctx, login, scopes...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...repo.Scope) *entity.User); ok {
		r0 = rf(ctx, login, scopes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...repo.Scope) error); ok {
		r1 = rf(ctx, login, scopes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_FindUserByUsernameOrEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsernameOrEmail'
type UserRepositoryMock_FindUserByUsernameOrEmail_Call struct {
	*mock.Call
}

// FindUserByUsernameOrEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - scopes ...repo.Scope
func (_e *UserRepositoryMock_Expecter) FindUserByUsernameOrEmail(ctx interface{}, login interface{}, scopes ...interface{}) *UserRepositoryMock_FindUserByUsernameOrEmail_Call {
	return &UserRepositoryMock_FindUserByUsernameOrEmail_Call{Call: _e.mock.On("FindUserByUsernameOrEmail",
		append([]interface{}{ctx, login}, scopes...)...)}
}

func (_c *UserRepositoryMock_FindUserByUsernameOrEmail_Call) Run(run func(ctx context.Context, login string, scopes ...repo.Scope)) *UserRepositoryMock_FindUserByUsernameOrEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repo.Scope, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(repo.Scope)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *UserRepositoryMock_FindUserByUsernameOrEmail_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_FindUserByUsernameOrEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_FindUserByUsernameOrEmail_Call) RunAndReturn(run func(context.Context, string, ...repo.Scope) (*entity.User, error)) *UserRepositoryMock_FindUserByUsernameOrEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *UserRepositoryMock) UpdateUser(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryMock_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserRepositoryMock_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *UserRepositoryMock_Expecter) UpdateUser(ctx interface{}, user interface{}) *UserRepositoryMock_UpdateUser_Call {
	return &UserRepositoryMock_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *UserRepositoryMock_UpdateUser_Call) Run(run func(ctx context.Context, user *entity.User)) *UserRepositoryMock_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserRepositoryMock_UpdateUser_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryMock_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryMock_UpdateUser_Call) RunAndReturn(run func(context.Context, *entity.User) (*entity.User, error)) *UserRepositoryMock_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithRolePreload provides a mock function with no fields
func (_m *UserRepositoryMock) WithRolePreload() repo.Scope {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithRolePreload")
	}

	var r0 repo.Scope
	if rf, ok := ret.Get(0).(func() repo.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.Scope)
		}
	}

	return r0
}

// UserRepositoryMock_WithRolePreload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithRolePreload'
type UserRepositoryMock_WithRolePreload_Call struct {
	*mock.Call
}

// WithRolePreload is a helper method to define mock.On call
func (_e *UserRepositoryMock_Expecter) WithRolePreload() *UserRepositoryMock_WithRolePreload_Call {
	return &UserRepositoryMock_WithRolePreload_Call{Call: _e.mock.On("WithRolePreload")}
}

func (_c *UserRepositoryMock_WithRolePreload_Call) Run(run func()) *UserRepositoryMock_WithRolePreload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserRepositoryMock_WithRolePreload_Call) Return(_a0 repo.Scope) *UserRepositoryMock_WithRolePreload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryMock_WithRolePreload_Call) RunAndReturn(run func() repo.Scope) *UserRepositoryMock_WithRolePreload_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
