version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: cmd/api/main.go
    flags:
      - -mod=readonly
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_{{- title .Os }}-{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README.md'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: mandarine-io
    name: backend
  prerelease: auto
  draft: false