with-expecter: true
issue-845-fix: true
resolve-type-alias: false
mockname: "{{.InterfaceName}}Mock"
filename: "{{.InterfaceNameSnake}}.go"
outpkg: "mock"
dir: "{{.InterfaceDir}}/mock"
packages:
  github.com/mandarine-io/backend/internal/infrastructure/cache:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/infrastructure/locale:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/infrastructure/pubsub:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/infrastructure/s3:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/infrastructure/smtp:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/infrastructure/template:
    config:
      include-regex: ".*"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/persistence/repo:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/service/domain:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/internal/service/infrastructure:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/third_party/geocoding:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"
  github.com/mandarine-io/backend/third_party/oauth:
    config:
      include-regex: ".*"
      exclude-regex: ".*Option"
      filename: "{{.InterfaceNameSnake}}.go"