version: '3.8'

networks:
  mandarine-integration-test-net:

services:
  ################################
  ########## PostgreSQL ##########
  ################################
  postgres:
    image: postgis/postgis:17-3.5-alpine
    container_name: mandarine-integration-test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${APP_TEST_POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${APP_TEST_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${APP_TEST_POSTGRES_DB:-mandarine}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - '${APP_TEST_POSTGRES_PORT:-25432}:5432'
    networks:
      - mandarine-integration-test-net

  ###########################
  ########## Redis ##########
  ###########################
  redis:
    image: redis/redis-stack:7.4.0-v2
    container_name: mandarine-integration-test-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${APP_TEST_REDIS_PASSWORD:-password}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - '${APP_TEST_REDIS_PORT:-26379}:6379'
    networks:
      - mandarine-integration-test-net

  ###########################
  ########## Minio ##########
  ###########################
  minio:
    image: bitnami/minio:2024.12.18
    container_name: mandarine-integration-test-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${APP_TEST_MINIO_ACCESSKEY:-admin}
      MINIO_ROOT_PASSWORD: ${APP_TEST_MINIO_SECRETKEY:-Password_10}
      MINIO_DEFAULT_BUCKETS: ${APP_TEST_MINIO_BUCKET:-mandarine}
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - '${APP_TEST_MINIO_PORT:-29000}:9000'
    networks:
      - mandarine-integration-test-net

  #############################
  ########## Mailhog ##########
  #############################
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mandarine-integration-test-mailhog
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -T5 -qO- http://localhost:8025 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - '${APP_TEST_MAILHOG_SMTPPORT:-21025}:1025'
      - '${APP_TEST_MAILHOG_APIPORT:-28025}:8025'
    networks:
      - mandarine-integration-test-net
