version: '3.8'

networks:
  mandarine-dev-net:

volumes:
  mandarine-dev-postgres-data:
  mandarine-dev-redis-data:
  mandarine-dev-minio-data:

#secrets:
#  postgres-password:
#    file: ${MANDARINE_POSTGRES__PASSWORD_FILE}
#  redis-password:
#    file: ${MANDARINE_REDIS__PASSWORD_FILE}
#  minio-secret-key:
#    file: ${MANDARINE_MINIO__SECRET_KEY_FILE}

services:
  ################################
  ########## PostgreSQL ##########
  ################################
  postgres:
    image: postgis/postgis:17-3.4-alpine
    container_name: mandarine-dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MANDARINE_POSTGRES__USERNAME}
      POSTGRES_PASSWORD: ${MANDARINE_POSTGRES__PASSWORD}
      #      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${MANDARINE_POSTGRES__DB_NAME}
#    secrets:
#      - postgres-password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_POSTGRES__PORT}:5432
    volumes:
      - mandarine-dev-postgres-data:/var/lib/postgresql/data
    networks:
      - mandarine-dev-net

  ###########################
  ########## Redis ##########
  ###########################
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: mandarine-dev-redis
    restart: unless-stopped
    environment:
      REDIS_USER: ${MANDARINE_REDIS__USERNAME}
      REDIS_PASSWORD: ${MANDARINE_REDIS__PASSWORD}
      #      REDIS_PASSWORD_FILE: /run/secrets/redis-password
      REDIS_ARGS: '--requirepass ${MANDARINE_REDIS__PASSWORD} --user ${MANDARINE_REDIS__USERNAME} on >${MANDARINE_REDIS__PASSWORD} ~* allcommands'
#    secrets:
#      - redis-password
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_REDIS__PORT}:6379
      - ${MANDARINE_REDIS__UI_PORT}:8001
    volumes:
      - mandarine-dev-redis-data:/data
    networks:
      - mandarine-dev-net

  ###########################
  ########## Minio ##########
  ###########################
  minio:
    image: bitnami/minio:2024.8.3
    container_name: mandarine-dev-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MANDARINE_MINIO__ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MANDARINE_MINIO__SECRET_KEY}
      #      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-secret-key
      MINIO_DEFAULT_BUCKETS: ${MANDARINE_MINIO__BUCKET_NAME}
#    secrets:
#      - minio-secret-key
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_MINIO__PORT}:9000
      - ${MANDARINE_MINIO__UI_PORT}:9001
    volumes:
      - mandarine-dev-minio-data:/bitnami/minio/data
    networks:
      - mandarine-dev-net

  ###########################
  ######### Backend #########
  ###########################
  backend:
    image: ghcr.io/mandarine-io/backend:${MANDARINE_SERVER__VERSION}
    container_name: mandarine-dev-backend
    restart: unless-stopped
    environment:
      MANDARINE_SERVER__VERSION: ${MANDARINE_SERVER__VERSION}
    env_file:
      - .env
    networks:
      - mandarine-dev-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  #################################
  ######### Reverse Proxy #########
  #################################
  reverse-proxy:
    image: nginx:1.27.2-alpine3.20-slim
    container_name: mandarine-dev-reverse-proxy
    restart: unless-stopped
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ 'CMD-SHELL', 'nc -z localhost 80 || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_REVERSE_PROXY__PORT}:80
    networks:
      - mandarine-dev-net
    depends_on:
      backend:
        condition: service_started