version: '3.8'

networks:
  mandarine-local-net:

volumes:
  mandarine-local-postgres-data:
  mandarine-local-redis-data:
  mandarine-local-minio-data:

services:
  ################################
  ########## PostgreSQL ##########
  ################################
  postgres:
    image: postgis/postgis:17-3.4-alpine
    container_name: mandarine-local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: LMRdskYdRNdXA0m1YK3stPFWAciSiwkvQVOZNebYvFI=
      POSTGRES_DB: mandarine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - 15432:5432
    volumes:
      - mandarine-local-postgres-data:/var/lib/postgresql/data
    networks:
      - mandarine-local-net

  ###########################
  ########## Redis ##########
  ###########################
  redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: mandarine-local-redis
    restart: unless-stopped
    environment:
      REDIS_USER: admin
      REDIS_PASSWORD: r8E3YuDeCHXWiNOGTz5uqpCJyYeuvZLWokSalMjfHeQ=
      REDIS_ARGS: |
        --requirepass r8E3YuDeCHXWiNOGTz5uqpCJyYeuvZLWokSalMjfHeQ= --user admin on >r8E3YuDeCHXWiNOGTz5uqpCJyYeuvZLWokSalMjfHeQ= ~* allcommands
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - 16379:6379
      - 18001:8001
    volumes:
      - mandarine-local-redis-data:/data
    networks:
      - mandarine-local-net

  ###########################
  ########## Minio ##########
  ###########################
  minio:
    image: bitnami/minio:2024.8.3
    container_name: mandarine-local-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: WZuWsLUF+dkSJCn80R/bIeYSgurfEH6Xq3vqmLgX9RA=
      MINIO_DEFAULT_BUCKETS: mandarine
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - 19000:9000
      - 19001:9001
    volumes:
      - mandarine-local-minio-data:/bitnami/minio/data
    networks:
      - mandarine-local-net