// Code generated by mockery v2.46.3. DO NOT EDIT.

package mock

import (
	context "context"

	dto "github.com/mandarine-io/Backend/internal/domain/dto"
	language "golang.org/x/text/language"

	mock "github.com/stretchr/testify/mock"
)

// GeocodingServiceMock is an autogenerated mock type for the GeocodingService type
type GeocodingServiceMock struct {
	mock.Mock
}

type GeocodingServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GeocodingServiceMock) EXPECT() *GeocodingServiceMock_Expecter {
	return &GeocodingServiceMock_Expecter{mock: &_m.Mock}
}

// Geocode provides a mock function with given fields: ctx, input, lang
func (_m *GeocodingServiceMock) Geocode(ctx context.Context, input dto.GeocodingInput, lang language.Tag) (dto.GeocodingOutput, error) {
	ret := _m.Called(ctx, input, lang)

	if len(ret) == 0 {
		panic("no return value specified for Geocode")
	}

	var r0 dto.GeocodingOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GeocodingInput, language.Tag) (dto.GeocodingOutput, error)); ok {
		return rf(ctx, input, lang)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GeocodingInput, language.Tag) dto.GeocodingOutput); ok {
		r0 = rf(ctx, input, lang)
	} else {
		r0 = ret.Get(0).(dto.GeocodingOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GeocodingInput, language.Tag) error); ok {
		r1 = rf(ctx, input, lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeocodingServiceMock_Geocode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Geocode'
type GeocodingServiceMock_Geocode_Call struct {
	*mock.Call
}

// Geocode is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.GeocodingInput
//   - lang language.Tag
func (_e *GeocodingServiceMock_Expecter) Geocode(ctx interface{}, input interface{}, lang interface{}) *GeocodingServiceMock_Geocode_Call {
	return &GeocodingServiceMock_Geocode_Call{Call: _e.mock.On("Geocode", ctx, input, lang)}
}

func (_c *GeocodingServiceMock_Geocode_Call) Run(run func(ctx context.Context, input dto.GeocodingInput, lang language.Tag)) *GeocodingServiceMock_Geocode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.GeocodingInput), args[2].(language.Tag))
	})
	return _c
}

func (_c *GeocodingServiceMock_Geocode_Call) Return(_a0 dto.GeocodingOutput, _a1 error) *GeocodingServiceMock_Geocode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeocodingServiceMock_Geocode_Call) RunAndReturn(run func(context.Context, dto.GeocodingInput, language.Tag) (dto.GeocodingOutput, error)) *GeocodingServiceMock_Geocode_Call {
	_c.Call.Return(run)
	return _c
}

// ReverseGeocode provides a mock function with given fields: ctx, input, lang
func (_m *GeocodingServiceMock) ReverseGeocode(ctx context.Context, input dto.ReverseGeocodingInput, lang language.Tag) (dto.ReverseGeocodingOutput, error) {
	ret := _m.Called(ctx, input, lang)

	if len(ret) == 0 {
		panic("no return value specified for ReverseGeocode")
	}

	var r0 dto.ReverseGeocodingOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReverseGeocodingInput, language.Tag) (dto.ReverseGeocodingOutput, error)); ok {
		return rf(ctx, input, lang)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReverseGeocodingInput, language.Tag) dto.ReverseGeocodingOutput); ok {
		r0 = rf(ctx, input, lang)
	} else {
		r0 = ret.Get(0).(dto.ReverseGeocodingOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReverseGeocodingInput, language.Tag) error); ok {
		r1 = rf(ctx, input, lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeocodingServiceMock_ReverseGeocode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReverseGeocode'
type GeocodingServiceMock_ReverseGeocode_Call struct {
	*mock.Call
}

// ReverseGeocode is a helper method to define mock.On call
//   - ctx context.Context
//   - input dto.ReverseGeocodingInput
//   - lang language.Tag
func (_e *GeocodingServiceMock_Expecter) ReverseGeocode(ctx interface{}, input interface{}, lang interface{}) *GeocodingServiceMock_ReverseGeocode_Call {
	return &GeocodingServiceMock_ReverseGeocode_Call{Call: _e.mock.On("ReverseGeocode", ctx, input, lang)}
}

func (_c *GeocodingServiceMock_ReverseGeocode_Call) Run(run func(ctx context.Context, input dto.ReverseGeocodingInput, lang language.Tag)) *GeocodingServiceMock_ReverseGeocode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ReverseGeocodingInput), args[2].(language.Tag))
	})
	return _c
}

func (_c *GeocodingServiceMock_ReverseGeocode_Call) Return(_a0 dto.ReverseGeocodingOutput, _a1 error) *GeocodingServiceMock_ReverseGeocode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeocodingServiceMock_ReverseGeocode_Call) RunAndReturn(run func(context.Context, dto.ReverseGeocodingInput, language.Tag) (dto.ReverseGeocodingOutput, error)) *GeocodingServiceMock_ReverseGeocode_Call {
	_c.Call.Return(run)
	return _c
}

// NewGeocodingServiceMock creates a new instance of GeocodingServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeocodingServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeocodingServiceMock {
	mock := &GeocodingServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
