name: Check changes
description: Check for changes in a directory
inputs:
  directory:
    description: 'Directory to check for changes'
    required: true
    type: boolean
outputs:
  changes:
    description: 'True if changes were found'
    value: ${{ steps.changed-files.outputs.any_changed }}
runs:
  using: composite
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Get all changed files in ${{ matrix.directory }}
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          ${{ inputs.directory }}/**