name: Check changes
description: Check for changes in a directory
inputs:
  directory:
    description: 'Directory to check for changes'
    required: true
    type: boolean
outputs:
  changes:
    description: 'True if changes were found'
    value: ${{ steps.check-changes.outputs.changes-result }}
runs:
  using: composite
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Check for changes in ${{ inputs.directory }}
      id: check-changes
      shell: bash
      run: |
        if git cat-file commit ${{ github.event.before }} >/dev/null 2>&1 && git cat-file commit ${{ github.sha }} >/dev/null 2>&1; then
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ${{ inputs.directory }} | tee changed_files.txt
          if [ ! -s changed_files.txt ]; then
            echo "changes-result=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes-result=true" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "changes-result=false" >> "$GITHUB_OUTPUT"
        fi