version: '3.8'

networks:
  mandarine-local-net:

volumes:
  mandarine-local-postgres-data:
  mandarine-local-redis-data:
  mandarine-local-minio-data:

secrets:
  postgres-password:
    file: ${MANDARINE_POSTGRES__PASSWORD_FILE}
  redis-password:
    file: ${MANDARINE_REDIS__PASSWORD_FILE}
  minio-secret-key:
    file: ${MANDARINE_MINIO__SECRET_KEY_FILE}

services:
  ################################
  ########## PostgreSQL ##########
  ################################
  postgres:
    build:
      context: .
      dockerfile: images/postgis.Dockerfile
    image: mandarine/postgis:17.0
    container_name: mandarine-local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MANDARINE_POSTGRES__USERNAME}
      POSTGRES_PASSWORD: ${MANDARINE_POSTGRES__PASSWORD}
      #      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: ${MANDARINE_POSTGRES__DB_NAME}
    secrets:
      - postgres-password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_POSTGRES__PORT}:5432
    volumes:
      - mandarine-local-postgres-data:/var/lib/postgresql/data
    networks:
      - mandarine-local-net

  ###########################
  ########## Redis ##########
  ###########################
  redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: mandarine-local-redis
    restart: unless-stopped
    environment:
      REDIS_USER: ${MANDARINE_REDIS__USERNAME}
      REDIS_PASSWORD: ${MANDARINE_REDIS__PASSWORD}
      #      REDIS_PASSWORD_FILE: /run/secrets/redis-password
      REDIS_ARGS: '--requirepass ${MANDARINE_REDIS__PASSWORD} --user ${MANDARINE_REDIS__USERNAME} on >${MANDARINE_REDIS__PASSWORD} ~* allcommands'
    secrets:
      - redis-password
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_REDIS__PORT}:6379
      - ${MANDARINE_REDIS__UI_PORT}:8001
    volumes:
      - mandarine-local-redis-data:/data
    networks:
      - mandarine-local-net

  ###########################
  ########## Minio ##########
  ###########################
  minio:
    image: bitnami/minio:2024.8.3
    container_name: mandarine-local-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MANDARINE_MINIO__ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MANDARINE_MINIO__SECRET_KEY}
      #      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio-secret-key
      MINIO_DEFAULT_BUCKETS: ${MANDARINE_MINIO__BUCKET_NAME}
    secrets:
      - minio-secret-key
    healthcheck:
      test: [ "CMD-SHELL", "mc ready local" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - ${MANDARINE_MINIO__PORT}:9000
      - ${MANDARINE_MINIO__UI_PORT}:9001
    volumes:
      - mandarine-local-minio-data:/bitnami/minio/data
    networks:
      - mandarine-local-net

