server:
  name: mandarine-server
  port: 8080
  external_origin: https://dev.mandarine-app.ru/api
  mode: development
  version: 0.0.0
  max_request_size: 500
postgres:
  host: postgres
  port: 5432
  username:
  password:
  db_name:
redis:
  host: redis
  port: 6379
  username: default
  password:
  db_index: 0
minio:
  host: minio
  port: 9000
  access_key:
  secret_key:
  bucket_name:
smtp:
  host: smtp.yandex.ru
  port: 465
  username:
  password:
  ssl: true
  from: Mandarine <mandarine-app@yandex.ru>
websocket:
  pool_size: 1024
oauth_client:
  google:
    client_id:
    client_secret:
  yandex:
    client_id:
    client_secret:
  mail_ru:
    client_id:
    client_secret:
cache:
  ttl: 120
security:
  jwt:
    secret:
    access_token_ttl: 3600
    refresh_token_ttl: 86400
  otp:
    length: 6
    ttl: 600
  rate_limit:
    rps: 100
locale:
  path: locales
  language: ru
template:
  path: templates
migrations:
  path: migrations
logger:
  level: debug
  console:
    enable: true
    encoding: text
  file:
    enable: true
    dir_path: logs
    max_size: 1
    max_age: 30

