server:
  name: mandarine-server
  port: 8000
  external_origin: rest://localhost:8000
  mode: local
  version: 0.0.0

database:
  postgres:
    enabled: false
    host: localhost
    port: 5432
    username: 
    password: 
    db_name: 
  cockroachdb:
    enabled: false
    host: localhost
    port: 26257
    username: 
    password: 
    db_name: 

cache:
  memory:
    enabled: false
  memcached:
    enabled: false
    host: localhost
    port: 11211
    username: default
    password: 
  redis:
    enabled: false
    host: localhost
    port: 6379
    username: default
    password: 
    db_index: 0
  ttl: 120

s3:
  minio:
    enabled: false
    host: localhost
    port: 9000
    access_key: 
    secret_key: 
    bucket_name: 
  aws:
    enabled: false
    host: 
    port: 443
    access_key: 
    secret_key: 
    bucket_name: 
    region: 

smtp:
  host: 
  port:
  username: 
  password: 
  ssl: true
  from: 'Mandarine <mandarine-app@yandex.ru>'

websocket:
  pool_size: 1024

oauth_provider:
  google:
    client_id: 
    client_secret: 
  yandex:
    client_id: 
    client_secret: 
  mail_ru:
    client_id: 
    client_secret: 

jwt:
  secret: 
  access_token_ttl: 3600
  refresh_token_ttl: 86400

otp:
  length: 6
  ttl: 600

http:
  rps: 100
  request_size_limit: 500

locale:
  path: locales
  language: ru

template:
  path: templates

migrations:
  path: migrations

logger:
  level: info
  console:
    enable: false
    encoding: text
  file:
    enable: false
    dir_path: logs
    max_size: 100
    max_age: 30
