cache:
  ttl: 120
  type: memory
  redis:
    address:
    dbindex: 0
    password:
    username: default
database:
  type: postgres
  postgres:
    address:
    dbname:
    password:
    username:
locale:
  language: ru
  path: locales
logger:
  console:
    enable: true
    encoding: text
  file:
    dirpath: logs
    enable: false
    maxage:
    maxsize:
  level: info
migrations:
  path: migrations
oauthclients:
  google:
    clientid: mock
    clientsecret: mock
  yandex:
    clientid: mock
    clientsecret: mock
  mailru:
    clientid: mock
    clientsecret: mock
pubsub:
  type: memory
  redis:
    address:
    dbindex: 0
    password:
    username: default
s3:
  type: minio
  minio:
    address:
    accesskey:
    bucket:
    secretkey:
security:
  jwt:
    accesstokenttl: 3600
    refreshtokenttl: 86400
    secret:
  otp:
    length: 6
    ttl: 300
server:
  externalorigin: http://localhost:8000
  maxrequestsize: 524288000
  mode: local
  name: server
  port: 8080
  rps: 100
  version: 0.0.0
smtp:
  from: 'Mandarine <no-reply@yandex.ru>'
  host:
  password:
  port:
  ssl:
  username:
template:
  path: templates
websocket:
  poolsize: 1024