server:
  name: mandarine-server
  port: 8080
  external_origin: http://localhost:8080
  mode: local
  version: 0.0.0
postgres:
  host: localhost
  port: 5432
  username:
  password:
  password_file:
  db_name:
redis:
  host: localhost
  port: 6379
  username: default
  password:
  password_file:
  db_index: 0
minio:
  host: localhost
  port: 9000
  access_key:
  secret_key:
  secret_key_file:
  bucket_name:
smtp:
  host: smtp.yandex.ru
  port: 465
  username:
  password:
  password_file:
  ssl: true
  from:
oauth_client:
  google:
    client_id:
    client_secret:
    client_secret_file:
  yandex:
    client_id:
    client_secret:
    client_secret_file:
  mail_ru:
    client_id:
    client_secret:
    client_secret_file:
cache:
  ttl: 120
security:
  jwt:
    secret:
    secret_file:
    access_token_ttl: 3600
    refresh_token_ttl: 86400
  otp:
    length: 6
    ttl: 600
  rate_limit:
    rps: 100
locale:
  path: locales
  language: ru
template:
  path: templates
migrations:
  path: migrations
logger:
  console:
    level: info
    encoding: text
  file:
    enable: true
    level: info
    dir_path: logs
    max_size: 1
    max_age: 30

