// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"
	model "github.com/mandarine-io/backend/pkg/model/v0"

	locale "github.com/mandarine-io/backend/internal/infrastructure/locale"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccountServiceMock is an autogenerated mock type for the AccountService type
type AccountServiceMock struct {
	mock.Mock
}

type AccountServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountServiceMock) EXPECT() *AccountServiceMock_Expecter {
	return &AccountServiceMock_Expecter{mock: &_m.Mock}
}

// DeleteAccount provides a mock function with given fields: ctx, id
func (_m *AccountServiceMock) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountServiceMock_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type AccountServiceMock_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountServiceMock_Expecter) DeleteAccount(ctx interface{}, id interface{}) *AccountServiceMock_DeleteAccount_Call {
	return &AccountServiceMock_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *AccountServiceMock_DeleteAccount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountServiceMock_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountServiceMock_DeleteAccount_Call) Return(_a0 error) *AccountServiceMock_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountServiceMock_DeleteAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AccountServiceMock_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *AccountServiceMock) GetAccount(ctx context.Context, id uuid.UUID) (model.AccountOutput, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 model.AccountOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.AccountOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.AccountOutput); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AccountOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountServiceMock_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountServiceMock_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountServiceMock_Expecter) GetAccount(ctx interface{}, id interface{}) *AccountServiceMock_GetAccount_Call {
	return &AccountServiceMock_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *AccountServiceMock_GetAccount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountServiceMock_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountServiceMock_GetAccount_Call) Return(_a0 model.AccountOutput, _a1 error) *AccountServiceMock_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountServiceMock_GetAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.AccountOutput, error)) *AccountServiceMock_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreAccount provides a mock function with given fields: ctx, id
func (_m *AccountServiceMock) RestoreAccount(ctx context.Context, id uuid.UUID) (model.AccountOutput, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAccount")
	}

	var r0 model.AccountOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.AccountOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.AccountOutput); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AccountOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountServiceMock_RestoreAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAccount'
type AccountServiceMock_RestoreAccount_Call struct {
	*mock.Call
}

// RestoreAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AccountServiceMock_Expecter) RestoreAccount(ctx interface{}, id interface{}) *AccountServiceMock_RestoreAccount_Call {
	return &AccountServiceMock_RestoreAccount_Call{Call: _e.mock.On("RestoreAccount", ctx, id)}
}

func (_c *AccountServiceMock_RestoreAccount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AccountServiceMock_RestoreAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccountServiceMock_RestoreAccount_Call) Return(_a0 model.AccountOutput, _a1 error) *AccountServiceMock_RestoreAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountServiceMock_RestoreAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.AccountOutput, error)) *AccountServiceMock_RestoreAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function with given fields: ctx, id, input
func (_m *AccountServiceMock) SetPassword(ctx context.Context, id uuid.UUID, input model.SetPasswordInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SetPasswordInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountServiceMock_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type AccountServiceMock_SetPassword_Call struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input model.SetPasswordInput
func (_e *AccountServiceMock_Expecter) SetPassword(ctx interface{}, id interface{}, input interface{}) *AccountServiceMock_SetPassword_Call {
	return &AccountServiceMock_SetPassword_Call{Call: _e.mock.On("SetPassword", ctx, id, input)}
}

func (_c *AccountServiceMock_SetPassword_Call) Run(run func(ctx context.Context, id uuid.UUID, input model.SetPasswordInput)) *AccountServiceMock_SetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SetPasswordInput))
	})
	return _c
}

func (_c *AccountServiceMock_SetPassword_Call) Return(_a0 error) *AccountServiceMock_SetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountServiceMock_SetPassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SetPasswordInput) error) *AccountServiceMock_SetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmail provides a mock function with given fields: ctx, id, input, localizer
func (_m *AccountServiceMock) UpdateEmail(ctx context.Context, id uuid.UUID, input model.UpdateEmailInput, localizer locale.Localizer) (model.AccountOutput, error) {
	ret := _m.Called(ctx, id, input, localizer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 model.AccountOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateEmailInput, locale.Localizer) (model.AccountOutput, error)); ok {
		return rf(ctx, id, input, localizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateEmailInput, locale.Localizer) model.AccountOutput); ok {
		r0 = rf(ctx, id, input, localizer)
	} else {
		r0 = ret.Get(0).(model.AccountOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateEmailInput, locale.Localizer) error); ok {
		r1 = rf(ctx, id, input, localizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountServiceMock_UpdateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmail'
type AccountServiceMock_UpdateEmail_Call struct {
	*mock.Call
}

// UpdateEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input model.UpdateEmailInput
//   - localizer locale.Localizer
func (_e *AccountServiceMock_Expecter) UpdateEmail(ctx interface{}, id interface{}, input interface{}, localizer interface{}) *AccountServiceMock_UpdateEmail_Call {
	return &AccountServiceMock_UpdateEmail_Call{Call: _e.mock.On("UpdateEmail", ctx, id, input, localizer)}
}

func (_c *AccountServiceMock_UpdateEmail_Call) Run(run func(ctx context.Context, id uuid.UUID, input model.UpdateEmailInput, localizer locale.Localizer)) *AccountServiceMock_UpdateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UpdateEmailInput), args[3].(locale.Localizer))
	})
	return _c
}

func (_c *AccountServiceMock_UpdateEmail_Call) Return(_a0 model.AccountOutput, _a1 error) *AccountServiceMock_UpdateEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountServiceMock_UpdateEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UpdateEmailInput, locale.Localizer) (model.AccountOutput, error)) *AccountServiceMock_UpdateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, input
func (_m *AccountServiceMock) UpdatePassword(ctx context.Context, id uuid.UUID, input model.UpdatePasswordInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdatePasswordInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountServiceMock_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type AccountServiceMock_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input model.UpdatePasswordInput
func (_e *AccountServiceMock_Expecter) UpdatePassword(ctx interface{}, id interface{}, input interface{}) *AccountServiceMock_UpdatePassword_Call {
	return &AccountServiceMock_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, input)}
}

func (_c *AccountServiceMock_UpdatePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, input model.UpdatePasswordInput)) *AccountServiceMock_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UpdatePasswordInput))
	})
	return _c
}

func (_c *AccountServiceMock_UpdatePassword_Call) Return(_a0 error) *AccountServiceMock_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountServiceMock_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UpdatePasswordInput) error) *AccountServiceMock_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUsername provides a mock function with given fields: ctx, id, input
func (_m *AccountServiceMock) UpdateUsername(ctx context.Context, id uuid.UUID, input model.UpdateUsernameInput) (model.AccountOutput, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUsername")
	}

	var r0 model.AccountOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateUsernameInput) (model.AccountOutput, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateUsernameInput) model.AccountOutput); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Get(0).(model.AccountOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateUsernameInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountServiceMock_UpdateUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsername'
type AccountServiceMock_UpdateUsername_Call struct {
	*mock.Call
}

// UpdateUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input model.UpdateUsernameInput
func (_e *AccountServiceMock_Expecter) UpdateUsername(ctx interface{}, id interface{}, input interface{}) *AccountServiceMock_UpdateUsername_Call {
	return &AccountServiceMock_UpdateUsername_Call{Call: _e.mock.On("UpdateUsername", ctx, id, input)}
}

func (_c *AccountServiceMock_UpdateUsername_Call) Run(run func(ctx context.Context, id uuid.UUID, input model.UpdateUsernameInput)) *AccountServiceMock_UpdateUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UpdateUsernameInput))
	})
	return _c
}

func (_c *AccountServiceMock_UpdateUsername_Call) Return(_a0 model.AccountOutput, _a1 error) *AccountServiceMock_UpdateUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountServiceMock_UpdateUsername_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UpdateUsernameInput) (model.AccountOutput, error)) *AccountServiceMock_UpdateUsername_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, id, input
func (_m *AccountServiceMock) VerifyEmail(ctx context.Context, id uuid.UUID, input model.VerifyEmailInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.VerifyEmailInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountServiceMock_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type AccountServiceMock_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input model.VerifyEmailInput
func (_e *AccountServiceMock_Expecter) VerifyEmail(ctx interface{}, id interface{}, input interface{}) *AccountServiceMock_VerifyEmail_Call {
	return &AccountServiceMock_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, id, input)}
}

func (_c *AccountServiceMock_VerifyEmail_Call) Run(run func(ctx context.Context, id uuid.UUID, input model.VerifyEmailInput)) *AccountServiceMock_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.VerifyEmailInput))
	})
	return _c
}

func (_c *AccountServiceMock_VerifyEmail_Call) Return(_a0 error) *AccountServiceMock_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountServiceMock_VerifyEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.VerifyEmailInput) error) *AccountServiceMock_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountServiceMock creates a new instance of AccountServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountServiceMock {
	mock := &AccountServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
