// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// EngineMock is an autogenerated mock type for the Engine type
type EngineMock struct {
	mock.Mock
}

type EngineMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EngineMock) EXPECT() *EngineMock_Expecter {
	return &EngineMock_Expecter{mock: &_m.Mock}
}

// RenderHTML provides a mock function with given fields: name, args
func (_m *EngineMock) RenderHTML(name string, args any) (string, error) {
	ret := _m.Called(name, args)

	if len(ret) == 0 {
		panic("no return value specified for RenderHTML")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, any) (string, error)); ok {
		return rf(name, args)
	}
	if rf, ok := ret.Get(0).(func(string, any) string); ok {
		r0 = rf(name, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, any) error); ok {
		r1 = rf(name, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EngineMock_RenderHTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderHTML'
type EngineMock_RenderHTML_Call struct {
	*mock.Call
}

// RenderHTML is a helper method to define mock.On call
//   - name string
//   - args any
func (_e *EngineMock_Expecter) RenderHTML(name interface{}, args interface{}) *EngineMock_RenderHTML_Call {
	return &EngineMock_RenderHTML_Call{Call: _e.mock.On("RenderHTML", name, args)}
}

func (_c *EngineMock_RenderHTML_Call) Run(run func(name string, args any)) *EngineMock_RenderHTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *EngineMock_RenderHTML_Call) Return(_a0 string, _a1 error) *EngineMock_RenderHTML_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EngineMock_RenderHTML_Call) RunAndReturn(run func(string, any) (string, error)) *EngineMock_RenderHTML_Call {
	_c.Call.Return(run)
	return _c
}

// RenderText provides a mock function with given fields: name, args
func (_m *EngineMock) RenderText(name string, args any) (string, error) {
	ret := _m.Called(name, args)

	if len(ret) == 0 {
		panic("no return value specified for RenderText")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, any) (string, error)); ok {
		return rf(name, args)
	}
	if rf, ok := ret.Get(0).(func(string, any) string); ok {
		r0 = rf(name, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, any) error); ok {
		r1 = rf(name, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EngineMock_RenderText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderText'
type EngineMock_RenderText_Call struct {
	*mock.Call
}

// RenderText is a helper method to define mock.On call
//   - name string
//   - args any
func (_e *EngineMock_Expecter) RenderText(name interface{}, args interface{}) *EngineMock_RenderText_Call {
	return &EngineMock_RenderText_Call{Call: _e.mock.On("RenderText", name, args)}
}

func (_c *EngineMock_RenderText_Call) Run(run func(name string, args any)) *EngineMock_RenderText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *EngineMock_RenderText_Call) Return(_a0 string, _a1 error) *EngineMock_RenderText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EngineMock_RenderText_Call) RunAndReturn(run func(string, any) (string, error)) *EngineMock_RenderText_Call {
	_c.Call.Return(run)
	return _c
}

// NewEngineMock creates a new instance of EngineMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngineMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EngineMock {
	mock := &EngineMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
