name: Create release
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if [[ "$tag" =~ rc[0-9]+$ ]]; then
            echo "Creating prerelease for tag: $tag"
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes \
                --prerelease
          else
            echo "Creating release for tag: $tag"
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes
          fi