name: Development library workflow
on:
  push:
    branches:
      - '!develop'
      - '!master'
      - '!main'
    paths:
      - 'baselib/**'
  pull_request:
  workflow_dispatch:
jobs:
  check-changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - baselib
    outputs:
      changes: ${{ steps.check-changes.outputs.changes }}
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4
      - name: Check for changes in ${{ matrix.directory }}
        id: check-changes
        uses: ./.github/actions/check-changes
        with:
          directory: ${{ matrix.directory }}
  format:
    needs:
      - check-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - baselib
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4
      - name: Format service
        id: format
        if: needs.check-changes.outputs.changes == 'true'
        uses: ./.github/actions/format-go
        with:
          working-directory: ${{ matrix.directory }}
  lint:
    needs:
      - check-changes
      - format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - baselib
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4
      - name: Lint service
        id: lint
        if: needs.check-changes.outputs.changes == 'true'
        uses: ./.github/actions/lint-go
        with:
          working-directory: ${{ matrix.directory }}
  unit-tests:
    needs:
      - check-changes
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - baselib
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4
      - name: Unit tests
        id: unit-tests
        if: needs.check-changes.outputs.changes == 'true'
        uses: ./.github/actions/test-with-allure-go
        with:
          working-directory: ${{ matrix.directory }}
          test_dir: tests/unit/...
          publish_branch: gh-unit-tests-${{ matrix.directory }}-pages-dev
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}