name: Run load tests
on:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'Load test names. Example: ["test1.js", "test2.js"]'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        test: ${{ fromJSON(github.event.inputs.test_names)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Check if test exists
        run: |
          if [ ! -f "tests/load/${{ matrix.test }}" ]; then
            echo "Test tests/load/${{ matrix.test }} does not exist."
            exit 1
          fi
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Create test env file
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.TEST_ENV_FILE_CONTENT }}
          filename: ".env.test"
          working-directory: deploy/docker
      - name: Deploy test environment
        working-directory: deploy/docker
        run: docker compose -f docker-compose.test.yml --env-file .env.test up -d
      - name: Run load tests
        uses: grafana/run-k6-action@v1
        env:
          K6_WEB_DASHBOARD: true
          K6_WEB_DASHBOARD_EXPORT: logs/load-tests/${{ matrix.test }}/report.html
          BACKEND_HOSTNAME: localhost:8080
        with:
          path: tests/load/${{ matrix.test }}
          fail-fast: false
          flags: --profiling-enabled
      - name: Cleanup test environment
        working-directory: deploy/docker
        run: docker compose -f docker-compose.test.yml --env-file .env.test down
      - name: Archive load tests artifacts
        uses: actions/upload-artifact@main
        with:
          name: load-tests-${{ matrix.test }}
          path: logs/load-tests/${{ matrix.test }}